#!/usr/bin/env bash
# Install missing tools and symlink this repo's configs into place. Idempotent.
#   ./install.sh [--dry-run] [--no-packages] [--no-links]
# Existing files/dirs at a link target are moved to <target>.bak.<timestamp>.
set -euo pipefail

REPO=$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)
CFG=${XDG_CONFIG_HOME:-$HOME/.config}
DRY=0 PACKAGES=1 LINKS=1
for a in "$@"; do
  case $a in
    --dry-run) DRY=1 ;;
    --no-packages) PACKAGES=0 ;;
    --no-links) LINKS=0 ;;
    -h|--help) sed -n 2,4p "${BASH_SOURCE[0]}"; exit 0 ;;
    *) echo "unknown option: $a" >&2; exit 1 ;;
  esac
done

say() { printf '\033[36m==>\033[0m %s\n' "$*"; }
run() { if [ "$DRY" = 1 ]; then printf '   [dry] %s\n' "$*"; else "$@"; fi; }
have() { command -v "$1" >/dev/null 2>&1; }

# --- links --------------------------------------------------------------
link() { # link <src> <dst>
  local src=$1 dst=$2
  if [ -L "$dst" ] && [ "$(readlink "$dst")" = "$src" ]; then echo "   ok    $dst"; return; fi
  run mkdir -p "$(dirname "$dst")"
  if [ -e "$dst" ] || [ -L "$dst" ]; then
    run mv "$dst" "$dst.bak.$(date +%s)"
    echo "   moved $dst -> $dst.bak.*"
  fi
  run ln -s "$src" "$dst"
  echo "   link  $dst -> $src"
}

install_links() {
  say "linking configs"
  link "$REPO/nvim"               "$CFG/nvim"
  link "$REPO/k9s"                "$CFG/k9s"
  # herdr keybinds locate their helper scripts via readlink on this file
  link "$REPO/herdr/config.toml"  "$CFG/herdr/config.toml"
  link "$REPO/tmux.conf"          "$HOME/.tmux.conf"
  link "$REPO/pi"                 "$HOME/.pi"
  # claude/codex: link tracked files individually; ~/.claude and ~/.codex also hold secrets and runtime state
  seed() { # seed <repo-file> <target> (settings/config: rewritten per machine, so copy once, never link)
    if [ ! -e "$2" ]; then
      run mkdir -p "$(dirname "$2")"
      run cp "$1" "$2"
      echo "   seed  $2"
    else
      echo "   keep  $2 (exists; diff against $1)"
    fi
  }
  seed "$REPO/codex/config.toml"    "$HOME/.codex/config.toml"
  # claude has two profiles (default account + ~/.claude-private, switched via
  # CLAUDE_CONFIG_DIR); both get the same repo-managed files, independently
  local cd
  for cd in "$HOME/.claude" "$HOME/.claude-private"; do
    seed "$REPO/claude/settings.json" "$cd/settings.json"
    link "$REPO/claude/scripts" "$cd/scripts"
    link "$REPO/hooks/secret-guard.sh" "$cd/hooks/secret-guard.sh"
  done
  link "$REPO/hooks/secret-guard.sh" "$HOME/.codex/hooks/secret-guard.sh"
  # skills/ is organized by category (skills/<category>/<name>); tools want a flat skills dir, so link by basename
  local s
  for s in "$REPO"/skills/*/*/; do
    for cd in "$HOME/.claude" "$HOME/.claude-private"; do
      link "${s%/}" "$cd/skills/$(basename "$s")"
    done
    link "${s%/}" "$HOME/.codex/skills/$(basename "$s")"
  done
  # codex-only hook (no claude equivalent: claude tracing goes through the
  # native mlflow-tracing marketplace plugin instead), so it lives under
  # codex/hooks/, not the shared hooks/ dir
  link "$REPO/codex/hooks/mlflow-codex-notify.sh" "$HOME/.codex/hooks/mlflow-codex-notify.sh"
  # codex's herdr hook lives at ~/.codex/ directly (not ~/.codex/hooks/) and its content
  # is codex-specific (generated by `herdr integration install codex`), unlike claude's
  # equivalent which stays untracked/gitignored and herdr-regenerated on demand
  link "$REPO/codex/herdr-agent-state.sh" "$HOME/.codex/herdr-agent-state.sh"
}

# --- packages -----------------------------------------------------------
# command:brew-formula
BREW_PKGS="git:git nvim:neovim tmux:tmux k9s:k9s jq:jq gh:gh fzf:fzf just:just lazygit:lazygit rg:ripgrep stylua:stylua shfmt:shfmt shellcheck:shellcheck node:node"

load_brew() {
  local b
  for b in /home/linuxbrew/.linuxbrew/bin/brew /opt/homebrew/bin/brew /usr/local/bin/brew; do
    [ -x "$b" ] && { eval "$("$b" shellenv)"; return 0; }
  done
  return 1
}

ensure_brew() {
  have brew && return
  load_brew && return
  say "installing Homebrew"
  run bash -c 'NONINTERACTIVE=1 /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"'
  [ "$DRY" = 1 ] || load_brew
}

install_packages() {
  say "packages"
  ensure_brew
  local pair cmd pkg
  for pair in $BREW_PKGS; do
    cmd=${pair%%:*} pkg=${pair##*:}
    if have "$cmd"; then echo "   ok    $cmd"; else run brew install "$pkg"; fi
  done
  have prettier || { have npm && run npm install -g prettier; }
  have claude || run bash -c 'curl -fsSL https://claude.ai/install.sh | bash'
  have herdr  || run bash -c 'curl -fsSL https://herdr.dev/install.sh | sh'
  have pi     || { have npm && run npm install -g @earendil-works/pi-coding-agent; }
  [ -d "$HOME/.tmux/plugins/tpm" ] || run git clone --depth 1 https://github.com/tmux-plugins/tpm "$HOME/.tmux/plugins/tpm"
}

# --- post ---------------------------------------------------------------
post() {
  say "post-install"
  run git -C "$REPO" submodule update --init --recursive
  # herdr owns <profile>/hooks/herdr-agent-state.sh, one per claude profile
  if have herdr; then
    local cd
    for cd in "$HOME/.claude" "$HOME/.claude-private"; do
      if [ ! -e "$cd/hooks/herdr-agent-state.sh" ]; then
        run env CLAUDE_CONFIG_DIR="$cd" herdr integration install claude \
          || echo "   warn: herdr claude integration failed for $cd"
      fi
    done
  fi
  local line="source \"$REPO/herdr/tab-title.zsh\""
  if [ -f "$HOME/.zshrc" ] && ! grep -qF "herdr/tab-title.zsh" "$HOME/.zshrc"; then
    if [ "$DRY" = 1 ]; then echo "   [dry] append to ~/.zshrc: $line"; else printf '\n%s\n' "$line" >> "$HOME/.zshrc"; fi
  fi
  # restore = install exactly what lazy-lock.json pins
  if have nvim; then run nvim --headless "+Lazy! restore" +qa; fi
  if [ -x "$HOME/.tmux/plugins/tpm/bin/install_plugins" ]; then run "$HOME/.tmux/plugins/tpm/bin/install_plugins"; fi
}

if [ "$PACKAGES" = 1 ]; then install_packages; fi
if [ "$LINKS" = 1 ]; then install_links; fi
if [ "$PACKAGES" = 1 ]; then post; fi
say "done"
